AllCops:
  Exclude:
    - 'db/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
